# -*- coding: utf-8 -*-
"""gen_msyh_font.py -- 生成 SmartKnob 的 LVGL 中文字库 (lv_font_msyh_16.c)

- 从 components/ui/pages/*.c + smartknob_ui.c 自动收集用到的全部字符
  (ASCII + 全角标点 + CJK), 字库永远与 UI 文案同步
- 渲染源: C:/Windows/Fonts/msyh.ttc (微软雅黑), 16px, 4bpp 灰度
- 输出: LVGL FMT_TXT / PLAIN / SPARSE_TINY 格式, 与旧字库结构完全一致

用法: python tools/gen_msyh_font.py
"""
import io
import os
import re
import glob
import sys

from PIL import Image, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES_DIR = os.path.join(ROOT, "components", "ui", "pages")
UI_MAIN = os.path.join(ROOT, "components", "ui", "smartknob_ui.c")
OUT = os.path.join(ROOT, "components", "ui", "fonts", "lv_font_msyh_16.c")
FONT_PATH = r"C:\Windows\Fonts\msyh.ttc"
PX = 16

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def collect_chars():
    r"""扫描 UI 源码, 解码 \xNN 转义, 返回用到的字符集"""
    used = set()

    def decode(sstr):
        out = bytearray()
        i = 0
        while i < len(sstr):
            if sstr[i] == "\\" and i + 1 < len(sstr) and sstr[i + 1] == "x":
                out.append(int(sstr[i + 2:i + 4], 16))
                i += 4
            else:
                out.extend(sstr[i].encode("utf-8"))
                i += 1
        return out.decode("utf-8", errors="replace")

    files = glob.glob(os.path.join(PAGES_DIR, "*.c")) + [UI_MAIN]
    for p in files:
        s = io.open(p, encoding="utf-8").read()
        for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', s):
            try:
                txt = decode(m.group(1))
            except Exception:
                continue
            used.update(txt)
    # 基础集: ASCII 可打印区 + 度/间隔号 + 常用备用
    base = {chr(c) for c in range(0x20, 0x7F)}
    base |= {chr(0xB0), chr(0xB7)}          # ° ·
    return sorted(base | used)


def render_glyph(font, ch):
    """返回 (adv_w_1_16px, box_w, box_h, ofs_x, ofs_y, bytes(bitmap 4bpp))"""
    adv = font.getlength(ch)
    try:
        bbox = font.getbbox(ch, anchor="la")
    except Exception:
        bbox = None
    if not bbox or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
        return max(1, round(adv * 16)), 0, 0, 0, 0, b""
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    from PIL import ImageDraw
    d = ImageDraw.Draw(img)
    d.text((-x0, -y0), ch, font=font, fill=255)
    px = img.load()
    # LVGL FMT_TXT 4bpp: 整个字形是连续的半字节流(首像素=高半字节),
    # 解码器 i 计数跨行持续, 不按行字节对齐 —— 按行补齐会导致奇数宽度字形花屏
    out = bytearray()
    acc = 0
    have_nib = False
    for y in range(h):
        for x in range(w):
            a = (px[x, y] * 15 + 127) // 255
            if not have_nib:
                acc = a
                have_nib = True
            else:
                out.append((acc << 4) | a)
                have_nib = False
    if have_nib:
        out.append(acc << 4)
    ofs_y = (font.getmetrics()[0]) - y0 - h   # ascent - bbox_top - box_h
    return max(1, round(adv * 16)), w, h, x0, ofs_y, bytes(out)


def main():
    chars = collect_chars()
    print("charset: %d chars" % len(chars))
    font = ImageFont.truetype(FONT_PATH, PX, index=0)
    ascent, descent = font.getmetrics()
    line_height, base_line = ascent + descent, descent
    print("metrics: ascent=%d descent=%d line_height=%d base_line=%d"
          % (ascent, descent, line_height, base_line))

    bitmaps = bytearray()
    dsc_lines = []
    cps = []
    dsc_lines.append(
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}, "
        "/* id = 0 保留 */")
    for ch in chars:
        cp = ord(ch)
        adv, w, h, ox, oy, bits = render_glyph(font, ch)
        gid = len(cps) + 1
        cps.append(cp)
        dsc_lines.append(
            "    {{.bitmap_index = {bi}, .adv_w = {adv}, .box_w = {w}, .box_h = {h}, "
            ".ofs_x = {ox}, .ofs_y = {oy}}},".format(bi=len(bitmaps), adv=adv, w=w, h=h, ox=ox, oy=oy))
        bitmaps += bits

    # unicode_list: 相对 range_start=0x20 的偏移
    ul_lines = []
    for i in range(0, len(cps), 8):
        row = ", ".join("0x%04x" % (cp - 0x20) for cp in cps[i:i + 8])
        ul_lines.append("    " + row + ",")
    ul_block = "static const uint16_t unicode_list[] = {\n%s\n};\n" % "\n".join(ul_lines)

    bmp_lines = []
    for i in range(0, len(bitmaps), 16):
        bmp_lines.append("    " + ", ".join("0x%02x" % b for b in bitmaps[i:i + 16]) + ",")
    bmp_block = "static const uint8_t glyph_bitmap[] = {\n%s\n};\n" % "\n".join(bmp_lines)

    src = """/* Microsoft YaHei {px}px, generated by tools/gen_msyh_font.py
 * 自动收集 UI 文案字符集, 勿手改; 新增文案后重新运行本脚本 */
#include "lvgl.h"

#if LVGL_VERSION_MAJOR >= 8
{bmp}
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{dsc}
}};

{ul}
static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x20, .range_length = 65536 - 0x20, .glyph_id_start = 1,
        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL,
        .list_length = {n}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }}
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .bitmap_format = 0,
}};

const lv_font_t lv_font_msyh_16 = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {lh},
    .base_line = {bl},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = &font_dsc
}};

#endif
""".format(px=PX, bmp=bmp_block, dsc="\n".join(dsc_lines), ul=ul_block,
           n=len(cps), lh=line_height, bl=base_line)

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(src)
    print("written %s (%d glyphs, bitmap %.1f KB)"
          % (OUT, len(cps), len(bitmaps) / 1024.0))


if __name__ == "__main__":
    main()